version: "3.9"
services:
  db:
    container_name: database
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: always

    ports:
      - "5432:5432"
    env_file:
      - ".env"
    volumes:
      - ./app/pgdata:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
      - .:/code
